### ISSUE TITLE
install.sh fails with "cuda_runtime_api.h: No such file or directory"

### ISSUE THREAD

**Issue by raedeus** [ghostlander/cudaminer-neoscrypt#3]
Hey there! Thanks for the great work here! I am getting this error on compile:

g++ -DHAVE_CONFIG_H -I.  -fopenmp  -pthread -fno-strict-aliasing  -I/usr/local/cuda/include    -O2 -fomit-frame-pointer -fno-stack-protector -march=native -falign-functions=16 -falign-jumps=16 -falign-labels=16 -MT cudaminer-crc32.o -MD -MP -MF .deps/cudaminer-crc32.Tpo -c -o cudaminer-crc32.o `test -f 'crc32.cpp' || echo './'`crc32.cpp
mv -f .deps/cudaminer-crc32.Tpo .deps/cudaminer-crc32.Po
g++ -DHAVE_CONFIG_H -I.  -fopenmp  -pthread -fno-strict-aliasing  -I/usr/local/cuda/include    -O2 -fomit-frame-pointer -fno-stack-protector -march=native -falign-functions=16 -falign-jumps=16 -falign-labels=16 -MT cudaminer-sha256.o -MD -MP -MF .deps/cudaminer-sha256.Tpo -c -o cudaminer-sha256.o `test -f 'sha256.cpp' || echo './'`sha256.cpp
mv -f .deps/cudaminer-sha256.Tpo .deps/cudaminer-sha256.Po
g++ -DHAVE_CONFIG_H -I.  -fopenmp  -pthread -fno-strict-aliasing  -I/usr/local/cuda/include    -O2 -fomit-frame-pointer -fno-stack-protector -march=native -falign-functions=16 -falign-jumps=16 -falign-labels=16 -MT cudaminer-cudaminer.o -MD -MP -MF .deps/cudaminer-cudaminer.Tpo -c -o cudaminer-cudaminer.o `test -f 'cudaminer.cpp' || echo './'`cudaminer.cpp
cudaminer.cpp:11:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include "cuda_runtime_api.h"

I'm running Arch, latest and greatest. Dependencies installed:

Nvidia:
 NVIDIA-SMI 390.25                 Driver Version: 390.25
Cuda:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85

Would love to get started with this and most of the heavy lifting has already been done by the mighty ghostlander! Any help would be greatly appreciated!

Thanks,

raedeus

**Comment by raedeus** [comment]
Just a thought... more research into this shows that all of the CUDA goodness is in /opt/cuda/ in the Arch implementation of CUDA 9.1. I can verify it's all in there and NOT in /usr/local/. Perhaps I need to alter some flags here?

Just thoughts. I am in fact an idiot. Please help if time permits.

Thanks again,

raedeus

**Comment by ghostlander** [comment]
sudo ln -s /opt/cuda /usr/local/cuda

The CUDA installer asks to create this symlink during an installation process.

**Comment by raedeus** [comment]
Indeed. I am an idiot.

Must have missed that in the arch install as it was all automated. The wiki had one line mentioning the possible need to link.

This solved the issue! Thanks!

raedeus

**Comment by turowicz** [comment]
You're not an idiot @raedeus, this issue has helped me solve my automation problem as well! ;)
